name: Export Posts from Notion to Jekyll

on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install libwebp-dev
        run: sudo apt-get update && sudo apt-get install -y libwebp-dev
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: checkout repo content to /blog/
        uses: actions/checkout@v4 # checkout the repository content to github runner.
        with:
          token: ${{ secrets.PAT }}
          path: ./blog
      - name: Download notion-to-jekyll
        uses: actions/checkout@v4 # checkout the repository content to github runner.
        with:
          repository: obrhubr/notion-to-jekyll
          token: ${{ secrets.PAT }}
          path: ./notion-to-jekyll
      - name: Install dependencies
        run: |
          cd ./notion-to-jekyll
          python -m pip install --upgrade pip
          pip install .
      - name: Run exporter
        run: |
          cd ./blog
          notion-to-jekyll --log
        env:
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            DB_ID: ${{ secrets.DB_ID }}
            LOGSNAG_TOKEN: ${{ secrets.LOGSNAG_TOKEN }}
      - name: Commit to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./blog
          commit_message: Automated update to blog posts
