name: fetch

on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client notion2md python-dotenv requests
      - name: Run exporter
        run: python short_export.py
        env:
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            SHORT_DB_ID: ${{ secrets.SHORT_DB_ID }}
      - name: Commit to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated update to notes
